version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: rails_dev
          POSTGRES_PASSWORD: 'aqwe123'
          POSTGRES_DB: todo_api_test
          DATABASE_URL: "postgres://ubuntu@localhost:5432/todo_api_test"
      - image: redis
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $TEST_FILES
      - run:
          name: run rubopcop
          command: bundle exec rubocop
      - run:
          name: run rails best practices
          command: bundle exec rails_best_practices .
      - run:
          name: run brakeman
          command: bundle exec brakeman -q
      - run:
          name: run bundle audit
          command: bundle exec bundle-audit check --update --ignore CVE-2015-9284

      - store_test_results:
          path: /tmp/test-results