version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: kolya
          POSTGRES_DB: todo_api_test
      - image: circleci/redis:5-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Set up DB
          command: bundle exec rake db:migrate

      - run:
          name: run tests
          command: bundle exec rspec
      - run:
          name: run rubopcop
          command: bundle exec rubocop
      - run:
          name: run rails best practices
          command: bundle exec rails_best_practices .
      - run:
          name: run brakeman
          command: bundle exec brakeman -q
      - run:
          name: run bundle audit
          command: bundle exec bundle-audit check --update


